### ISSUE TITLE
BackendSpecificError when retrieve device name

### ISSUE THREAD

**Issue by arjenzhou** [RustAudio/cpal#385]
environment:
- macOS 10.15.3
- rustc 1.42.0

When I call `Device.name()` in

```rust
use cpal::traits::DeviceTrait;
use cpal::traits::HostTrait;

fn main() {
    let host = cpal::default_host();
    let devices = host.devices().expect("error");
    for device in devices {
        let res = device.name();
        println!("{:#?}", res.expect(""));
    }
}
```
throws
```rust
Err(
    BackendSpecific {
        err: BackendSpecificError {
            description: "core foundation unexpectedly returned null string",
        },
    },
)
```
Full RUST_BACKTRACE
```rust
$ cargo run
   Compiling foo v0.1.0 (/Users/zhouyang/repos/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s
     Running `target/debug/foo`
thread 'main' panicked at ': BackendSpecific { err: BackendSpecificError { description: "core foundation unexpectedly returned null string" } }', src/main.rs:9:27
stack backtrace:
   0:        0x10b6f1535 - backtrace::backtrace::libunwind::trace::h5c84db184dbe55ed
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:        0x10b6f1535 - backtrace::backtrace::trace_unsynchronized::hfabf504f184a4062
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:        0x10b6f1535 - std::sys_common::backtrace::_print_fmt::hb18545a457444b58
                               at src/libstd/sys_common/backtrace.rs:77
   3:        0x10b6f1535 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff7732c2e44ef8b9
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x10b7077bd - core::fmt::ArgumentV1::show_usize::h0555723a314a596c
   5:        0x10b6efd1b - std::io::Write::write_fmt::ha39f6009af02b1d2
                               at src/libstd/io/mod.rs:1426
   6:        0x10b6f316a - std::sys_common::backtrace::_print::h5cfb8cdd320f1e64
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x10b6f316a - std::sys_common::backtrace::print::hef683e3bc77ce269
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x10b6f316a - std::panicking::default_hook::{{closure}}::h389f076017b5df43
                               at src/libstd/panicking.rs:204
   9:        0x10b6f2e6a - std::panicking::default_hook::h04b06ec20c41bf02
                               at src/libstd/panicking.rs:224
  10:        0x10b6f36fd - std::panicking::rust_panic_with_hook::hccde7faed9a5c398
                               at src/libstd/panicking.rs:472
  11:        0x10b6f32c2 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:        0x10b70b3df - core::panicking::panic_fmt::h272b9afd5b7b725a
                               at src/libcore/panicking.rs:85
  13:        0x10b70b2e5 - core::option::expect_none_failed::h2ce75daf7660504d
                               at src/libcore/option.rs:1199
  14:        0x10b6e394f - core::result::Result<T,E>::expect::h9a192cd3f252fb7b
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/result.rs:991
  15:        0x10b6e3549 - foo::main::h8471f542f5a0974a
                               at src/main.rs:9
  16:        0x10b6e3a52 - std::rt::lang_start::{{closure}}::h69d0a6af28ff0858
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  17:        0x10b6f3228 - std::rt::lang_start_internal::{{closure}}::hd38dd0e12f275c20
                               at src/libstd/rt.rs:52
  18:        0x10b6f3228 - std::panicking::try::do_call::hf2b35caddf59127c
                               at src/libstd/panicking.rs:305
  19:        0x10b6f484b - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  20:        0x10b6f3abe - std::panicking::try::hc278c045b5a17f13
                               at src/libstd/panicking.rs:281
  21:        0x10b6f3abe - std::panic::catch_unwind::h21f9aef85494420b
                               at src/libstd/panic.rs:394
  22:        0x10b6f3abe - std::rt::lang_start_internal::h8e563903bf99e7c1
                               at src/libstd/rt.rs:51
  23:        0x10b6e3a32 - std::rt::lang_start::hbc59a32010f9175a
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  24:        0x10b6e3642 - foo::main::h8471f542f5a0974a
```

**Comment by leecbaker** [comment]
I can't replicate this on Mac OS 12.3 / CPAL 0.15.3 / Rust 1.60.

**Comment by arjenzhou** [comment]
> I can't replicate this on Mac OS 12.3 / CPAL 0.15.3 / Rust 1.60.

Yes, it has been resolved.
