### ISSUE TITLE
Panicking in the output callback causes ALSA output stream drop to panic

### ISSUE THREAD

**Issue by Ralith** [RustAudio/cpal#484]
Example backtrace:
```
thread 'main' panicked at 'assertion failed: ret == 8', /home/ralith/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.12.1/src/host/alsa/mod.rs:130:9
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:497
   1: cpal::host::alsa::TriggerSender::wakeup
             at /home/ralith/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.12.1/src/host/alsa/mod.rs:130
   2: <cpal::host::alsa::Stream as core::ops::drop::Drop>::drop
             at /home/ralith/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.12.1/src/host/alsa/mod.rs:863
   3: core::ptr::drop_in_place
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ptr/mod.rs:184
   4: core::ptr::drop_in_place
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ptr/mod.rs:184
   5: core::ptr::drop_in_place
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ptr/mod.rs:184
   6: demo::main
             at ./examples/demo.rs:92
   7: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
```

I'm not sure what the best way to handle panics in the output callback is, but it looks like the current behavior isn't intended either.

**Comment by dzubybb** [comment]
I think i'm getting the same error. I'm using rodio to play some streams from internet, which is using cpal and alsa. It's running on micro computer NanoPi Neo with Armv7 cpu. When i start playback after some inactivity(about 2-8h) cpal code panics: 
```
thread 'main' panicked at 'assertion failed: `(left == right)`
Jun 27 18:54:28.035042 DietPi unitra-digital-rs[23877]:   left: `-1`,
Jun 27 18:54:28.035042 DietPi unitra-digital-rs[23877]:  right: `8`', /home/komp/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.15.1/src/host/alsa/mod.rs:145:9
```
My code is creating new default device and Sink in rodio.

My `/etc/asound.conf` :
```
pcm.!default {
    type plug
    slave.pcm "dmixer"
}

pcm.dmixer  {
    type dmix
    ipc_key 102434
    slave {
        pcm "hw:0,0"
        rate 44100
    }
    bindings {
        0 0
        1 1
    }
}

ctl.dmixer {
    type hw
    card 0
}
```
Any help will be appreciated.

**Comment by compenguy** [comment]
I'm seeing this in the unit tests for the redlux crate (actually [my fork of it](https://github.com/compenguy/redlux), which will turn into a PR to the official crate, once it works) when upgrading it from rodio 0.17 to 0.18 or higher:

```
running 2 tests
test play_m4a ... FAILED
test play_aac ... FAILED

failures:

---- play_m4a stdout ----
thread 'cpal_alsa_out' panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/time.rs:947:23:
cannot convert float seconds to Duration: value is either too big or NaN
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'play_m4a' panicked at /home/wpage/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cpal-0.15.3/src/host/alsa/mod.rs:143:9:
assertion `left == right` failed
  left: -1
 right: 8

---- play_aac stdout ----
thread 'cpal_alsa_out' panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/time.rs:947:23:
cannot convert float seconds to Duration: value is either too big or NaN
thread 'play_aac' panicked at /home/wpage/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cpal-0.15.3/src/host/alsa/mod.rs:143:9:
assertion `left == right` failed
  left: -1
 right: 8


failures:
    play_aac
    play_m4a

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.21s
```

The only change between unit tests passing and failing is the rodio version (0.17 passing, >=0.18 failing).

**Comment by roderickvd** [comment]
The drop behavior including this assertion has improved on master. Feel free to reopen if that didn't fix it.
