### ISSUE TITLE
Failed to build on Apple Sillicon

### ISSUE THREAD

**Issue by rbrigden** [RustAudio/cpal#532]
Hi! Trying to build and run the `record_wav` example on apple sillicon (M1), and running into a build issue. I can't seem to make much of the backtrace and I'm wondering if you would expect `cpal` to have fundamental issues running on the M1.

Thanks!

```
➜  cpal git:(master) RUST_BACKTRACE=full cargo run --example record_wav
   Compiling coreaudio-sys v0.2.6
error: failed to run custom build command for `coreaudio-sys v0.2.6`

Caused by:
  process didn't exit successfully: `/Users/monomoy/reckon/projects/cpal/target/debug/build/coreaudio-sys-7f64659f5c8c26d9/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=COREAUDIO_SDK_PATH
  cargo:rustc-link-lib=framework=AudioToolbox
  cargo:rustc-link-lib=framework=AudioToolbox
  cargo:rustc-link-lib=framework=CoreAudio
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  thread 'main' panicked at 'libclang error; possible causes include:
  - Invalid flag syntax
  - Unrecognized flags
  - Invalid flag arguments
  - File I/O errors
  - Host vs. target architecture mismatch
  If you encounter an error missing from this list, please file an issue or a PR!', /Users/monomoy/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.3/src/ir/context.rs:573:15
  stack backtrace:
  stack backtrace:
     0:        0x10100b790 - std::backtrace_rs::backtrace::libunwind::trace::hd6f36bbe74b935d3
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
     1:        0x10100b790 - std::backtrace_rs::backtrace::trace_unsynchronized::h40c5caab64410550
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x10100b790 - std::sys_common::backtrace::_print_fmt::hc4387b90c40b9cbe
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
     3:        0x10100b790 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb7980d26174b99cc
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
     4:        0x10102903c - core::fmt::write::hce37a9344a9aa8e7
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
     5:        0x101008564 - std::io::Write::write_fmt::h686eb8440ccc31c3
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
     6:        0x10100d5d4 - std::sys_common::backtrace::_print::h3a98c9f9404b2107
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
     7:        0x10100d5d4 - std::sys_common::backtrace::print::h013faaaec45a449b
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
     8:        0x10100d5d4 - std::panicking::default_hook::{{closure}}::hd8ecce238a238901
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
     9:        0x10100d2ac - std::panicking::default_hook::h4c3bbdaeee039651
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
    10:        0x10100db88 - std::panicking::rust_panic_with_hook::h140cbf507d3407f4
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
    11:        0x10100d764 - std::panicking::begin_panic_handler::{{closure}}::hb6a3220cf34e266a
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
    12:        0x10100bc48 - std::sys_common::backtrace::__rust_end_short_backtrace::hd5353dc16fba6ea5
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
    13:        0x10100d6cc - rust_begin_unwind
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
    14:        0x101032118 - core::panicking::panic_fmt::h0333f3235caab578
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
    15:        0x101032018 - core::option::expect_failed::hf0ddc7de4cc4d418
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1260:5
    16:        0x100dbff0c - core::option::Option<T>::expect::he4104ed8e399d763
                                 at /Users/monomoy/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:349:21
    17:        0x100cbac78 - bindgen::ir::context::BindgenContext::new::hcffa7ad4cce7ba7f
                                 at /Users/monomoy/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.3/src/ir/context.rs:567:13
    18:        0x100dd8e40 - bindgen::Bindings::generate::h972680baec1c216d
                                 at /Users/monomoy/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.3/src/lib.rs:2106:27
    19:        0x100dd733c - bindgen::Builder::generate::h5892e3e009ff2b6c
                                 at /Users/monomoy/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.3/src/lib.rs:1419:9
    20:        0x100c660c0 - build_script_build::build::hc6147fd2a9a681a0
                                 at /Users/monomoy/.cargo/registry/src/github.com-1ecc6299db9ec823/coreaudio-sys-0.2.6/build.rs:124:20
    21:        0x100c66544 - build_script_build::main::h6d36316394f2bd7a
                                 at /Users/monomoy/.cargo/registry/src/github.com-1ecc6299db9ec823/coreaudio-sys-0.2.6/build.rs:139:5
    22:        0x100c67988 - core::ops::function::FnOnce::call_once::h6d76773d838b02a4
                                 at /Users/monomoy/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
    23:        0x100c66a14 - std::sys_common::backtrace::__rust_begin_short_backtrace::h46bce80dac65b40a
                                 at /Users/monomoy/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
    24:        0x100c6705c - std::rt::lang_start::{{closure}}::hf973ef0d74aa18ed
                                 at /Users/monomoy/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
    25:        0x10100dfe0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h31d919e3ff759175
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259:13
    26:        0x10100dfe0 - std::panicking::try::do_call::h8e802964b4cf90f8
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
    27:        0x10100dfe0 - std::panicking::try::h7dd4cf36e113e9b8
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
    28:        0x10100dfe0 - std::panic::catch_unwind::h41c857b84450ac33
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
    29:        0x10100dfe0 - std::rt::lang_start_internal::h1c29856da483cadc
                                 at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51:25
    30:        0x100c67034 - std::rt::lang_start::hb8b5d938bb62be62
                                 at /Users/monomoy/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
    31:        0x100c665c4 - _main
```

**Comment by rbrigden** [comment]
My bad, this is a build failure for `coreaudio-sys v0.2.6` and not CPAL. For others facing this issue on apple sillicon -- you can follow an issue I opened in the coreaudio-sys repo [here](https://github.com/RustAudio/coreaudio-sys/issues/47)
